Style/Encoding:
    Enabled: true

Style/Lambda:
    EnforcedStyle: literal

Layout/AccessModifierIndentation:
    EnforcedStyle: indent
    IndentationWidth: 2

Layout/ArgumentAlignment:
    Enabled: true
    EnforcedStyle: with_fixed_indentation

Metrics/AbcSize:
    Enabled: false

Metrics/CyclomaticComplexity:
    Enabled: false

Metrics/BlockLength:
    Enabled: false

Metrics/ModuleLength:
    Max: 4000

Metrics/MethodLength:
    Max: 4000

Metrics/ClassLength:
    Max: 4000

Metrics/PerceivedComplexity:
    Enabled: false

Layout/ArrayAlignment:
    Enabled: true

Layout/AssignmentIndentation:
    Enabled: true
    IndentationWidth: 2

Layout/BeginEndAlignment:
    Enabled: true
    EnforcedStyleAlignWith: begin

Layout/BlockAlignment:
    Enabled: true
    EnforcedStyleAlignWith: start_of_block

Layout/CaseIndentation:
    Enabled: true
    IndentationWidth: 2

Layout/FirstArrayElementIndentation:
    Enabled: true

Layout/ClassStructure:
    Categories:
        association:
            - has_many
            - has_one
        attribute_macros:
            - attr_accessor
            - attr_reader
            - attr_writer
        macros:
            - validates
            - validate
        module_inclusion:
            - include
            - prepend
            - extend

Layout/FirstArgumentIndentation:
    EnforcedStyle: consistent

Layout/ExtraSpacing:
    AllowForAlignment: false

Layout/MultilineArrayLineBreaks:
    AllowMultilineFinalElement: false

Layout/MultilineMethodCallIndentation:
    EnforcedStyle: indented

Layout/MultilineMethodDefinitionBraceLayout:
    EnforcedStyle: new_line

Layout/MultilineHashBraceLayout:
    EnforcedStyle: symmetrical

Layout/MultilineAssignmentLayout:
    EnforcedStyle: same_line

Layout/EndAlignment:
    EnforcedStyleAlignWith: variable

Layout/FirstParameterIndentation:
    Enabled: true
    EnforcedStyle: align_parentheses

Layout/ClosingParenthesisIndentation:
    Enabled: true

Layout/IndentationWidth:
    Enabled: true
    Width: 2

inherit_mode:
    merge:
        - Exclude

AllCops:
    NewCops: enable
    Exclude:
        - 'config/**/*'
        - 'script/**/*'
        - 'bin/{rails,rake}'
        - '**/*.gemfile'
        - '**/*.gemspec'
        - '**/*.rake'
        - '**/*.ru'
        - '**/Gemfile'
        - '**/Rakefile'
        - scripts/**/*
